### PR TITLE
<Key /> component to generate kbd elements from keypresses

### PR DESCRIPTION
**Pull request by TheSecEng**
**Why**

Streamline writing keyboard shortcuts.

**What**
Implementation of a Key component. It allows you to write shortcuts in the form of `<Key k="Ctrl + Space" />` and produces the following

image

The implementation splits on `+`, trims the whitespace, then generates valid `<kbd></kbd>` to be inserted into the page.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Working on this locally. Not in a mergable state.

**Comment by FichteFoll** [comment]
@TheSecEng I updated the branch, fixed a couple bugs and added some key chord parsing how I imagined this feature to work, notably taking key bindings in ST's format. Turned out pretty well.

I know this would have been possible with Sphinx as well, but this is also one of the reason I was happy to move to Vuepress.

**Comment by FichteFoll** [comment]
Apparently I can't request a review from you, since you already opened the PR, but I didn't want to make a PR against your PR for such a "small" thing, so and assignment will do.

**Comment by jrappen** [comment]
Nice.

**Comment by TheSecEng** [comment]
Looks good to me, if not merged when I get time tonight. Will do. 

👍

**Pull request merged**
